-- MySQL Script generated by MySQL Workbench
-- 06/02/14 14:09:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IPEZ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IPEZ` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `IPEZ` ;

-- -----------------------------------------------------
-- Table `IPEZ`.`TClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TClient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(25) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  `newsletter` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `TClientcol_UNIQUE` (`mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPEZ`.`TClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TClient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(25) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  `newsletter` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `TClientcol_UNIQUE` (`mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPEZ`.`TEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TEvent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `date` DATE NOT NULL,
  `heure` TIME NOT NULL,
  `lieu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPEZ`.`TProduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TProduit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `nb_vente` INT NULL,
  `nb_stock` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPEZ`.`TTypeProduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TTypeProduit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `TProduit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TTypeProduit_TProduit1_idx` (`TProduit_id` ASC),
  CONSTRAINT `fk_TTypeProduit_TProduit1`
    FOREIGN KEY (`TProduit_id`)
    REFERENCES `IPEZ`.`TProduit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPEZ`.`TParticipation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TParticipation` (
  `TClient_id` INT NOT NULL,
  `TEvent_id` INT NOT NULL,
  INDEX `fk_TParticipation_TClient_idx` (`TClient_id` ASC),
  INDEX `fk_TParticipation_TEvent1_idx` (`TEvent_id` ASC),
  CONSTRAINT `fk_TParticipation_TClient`
    FOREIGN KEY (`TClient_id`)
    REFERENCES `IPEZ`.`TClient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TParticipation_TEvent1`
    FOREIGN KEY (`TEvent_id`)
    REFERENCES `IPEZ`.`TEvent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPEZ`.`TAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TAdmin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  `droits` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IPEZ`.`TTypeEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IPEZ`.`TTypeEvent` (
  `TEvent_id` INT NOT NULL,
  `TTypeProduit_id` INT NOT NULL,
  INDEX `fk_TTypeEvent_TEvent1_idx` (`TEvent_id` ASC),
  INDEX `fk_TTypeEvent_TTypeProduit1_idx` (`TTypeProduit_id` ASC),
  CONSTRAINT `fk_TTypeEvent_TEvent1`
    FOREIGN KEY (`TEvent_id`)
    REFERENCES `IPEZ`.`TEvent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TTypeEvent_TTypeProduit1`
    FOREIGN KEY (`TTypeProduit_id`)
    REFERENCES `IPEZ`.`TTypeProduit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
